"""
Base plugin for the different speech recognition tools.
Speech Plugins should inherits from the this base class.
"""
from abc import ABC, abstractmethod
from config import logger

class SpeechPlugin(ABC):
    """
    Base module for the plugins.
    """

    def __init__(self):
        self._logger = logger
    
    @abstractmethod
    def microphone_input(self):
        """
        This method should take the bytes coming from the microphone. 
        """
        pass

    @abstractmethod
    def output(self):
        """
        This method should output the text generated by the speech model.
        """
        pass